In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [3]:
arr1 = np.random.random((3,3,3))
print (arr1)

[[[0.6635303  0.84670358 0.33363337]
  [0.73712007 0.56539178 0.87547335]
  [0.84957087 0.93701963 0.51029665]]

 [[0.58361336 0.60972695 0.37445847]
  [0.70127788 0.75616746 0.94912276]
  [0.88402465 0.70365842 0.94419796]]

 [[0.59935946 0.24531924 0.82195024]
  [0.88424739 0.89860655 0.91093025]
  [0.57431041 0.92761278 0.66575837]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
arr2 = np.diag(1 + np.arange(4), k=-1)
print(arr2)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
arr3 = np.zeros((8,8), dtype=int)
arr3[1::2, ::2] = 1
arr3[::2,1::2] = 1
print(arr3)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
arr4 = np.random.random((5,5))

arr4max, arr4min = arr4.max(), arr4.min()

arr4 = (arr4 - arr4min)/(arr4max - arr4min)

print(arr4)

[[0.62294706 0.2342347  1.         0.37708172 0.77963746]
 [0.36885147 0.99391115 0.56415591 0.19584343 0.45907109]
 [0.61078942 0.5289359  0.08281014 0.44634489 0.01173224]
 [0.27905707 0.69703448 0.3678969  0.         0.39694791]
 [0.68505525 0.03955238 0.73623544 0.97812533 0.96148248]]


# 5.  How to find common values between two arrays?

In [9]:
a1 = np.random.randint(0,10,10)
print(a1)
a2 = np.random.randint(0,10,10)
print(a2)

print(np.intersect1d(a1,a2))

[4 0 1 3 3 4 2 7 6 9]
[1 0 5 3 6 8 8 1 3 5]
[0 1 3 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [11]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today = np.datetime64('today', 'D')
print(today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2020-07-25
2020-07-26
2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [19]:
A = np.random.randint(0,2,5)
print('A:',A)
B = np.random.randint(0,2,5)
print('B:',B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values

equal = np.allclose(A,B)

print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)

equal = np.array_equal(A,B)

print(equal)

A: [1 1 0 0 1]
B: [0 0 0 1 1]
False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [20]:
arr5 = np.random.random(10)

arr5[arr5.argmax()] = 0

print(arr5)

[0.47570961 0.34485254 0.27736547 0.46251666 0.54017435 0.26019869
 0.52279449 0.         0.58224119 0.58487625]


# 9. How to print all the values of an array?

# 10.Subtract the mean of each row of a matrix

In [35]:
arr6 = np.random.rand(5, 10)
arr7 = arr6 - arr6.mean(axis = 1, keepdims = True)
print(arr7)

[[-0.09577865  0.38125617 -0.19037701 -0.07377079 -0.28586245  0.23529816
  -0.22553101 -0.15896405  0.38633622  0.02739341]
 [ 0.40895739  0.13499402 -0.43229518  0.21815497  0.15863128 -0.19354105
  -0.31594474 -0.45759669  0.0883406   0.3902994 ]
 [-0.12155869 -0.04966586  0.22032394 -0.19831189  0.21758648 -0.03080135
  -0.64357538  0.05041365  0.29157946  0.26400964]
 [-0.41761061 -0.21143882 -0.16096743  0.10843799 -0.30048269  0.34198434
   0.15134084 -0.17037692  0.35423613  0.30487716]
 [-0.47018994 -0.02441428 -0.42530406 -0.3609018   0.38507234  0.04912857
   0.45644262  0.24120905  0.03667262  0.11228489]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [42]:
a = np.ones(10)
print(a)
b = np.random.randint(0,len(a),20)
print(b)
a += np.bincount(b, minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 6 6 7 5 6 5 2 9 2 1 7 9 8 8 3 2 3 9 4]
[2. 2. 4. 3. 2. 3. 4. 3. 3. 4.]


# 12.How to get the diagonal of a dot product?

In [44]:
arr_1 = np.random.uniform(0,1,(5,5))

arr_2 = np.random.uniform(0,1,(5,5))

print(np.einsum("ij,ji->i", arr_1, arr_2))

[0.75843822 1.21127741 1.40800065 1.14977644 1.09903639]


# 13.How to find the most frequent value in an array?

In [46]:
arr_3 = np.random.randint(0,10,50)
print(arr_3)
print(np.bincount(arr_3).argmax())

[2 4 2 2 8 9 7 9 6 6 3 2 2 3 4 0 2 5 7 0 3 7 5 1 2 4 9 8 6 5 1 3 1 0 5 2 2
 2 0 5 8 8 3 2 0 3 3 9 0 3]
2


# 14.How to get the n largest values of an array

In [51]:
arr_4 = np.arange(100)
np.random.shuffle(arr_4)
n = 7
print (arr_4[np.argsort(arr_4)[-n:]])

[93 94 95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [52]:
Z = np.array([("Hello", 2.5, 3),

("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T,

names='col1, col2, col3',

formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
